module.exports = {
  STOCK_ADDED: "STOCK_ADDED",
  STOCK_REMOVED: "STOCK_REMOVED",
  STOCK_RESERVED: "STOCK_RESERVED",
  RESERVATION_RELEASED: "RESERVATION_RELEASED",
  ORDER_CONFIRMED: "ORDER_CONFIRMED",
  ORDER_CANCELLED: "ORDER_CANCELLED",
  MANUAL_ADJUSTMENT: "MANUAL_ADJUSTMENT",
};